version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: music-streamer
    ports:
      - "3000:5000"  # Adjust if your Node app uses a different port
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/music-db  # Match this with your MongoDB connection string

  mongo:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
